### ISSUE TITLE
Removes logo even when that box is unchecked

### ISSUE THREAD

**Issue by fcherman** [Fogest/Email-Print-Page-Cleaner#1]
Great extension, however, it's removing the logo even when that option has been unchecked. I wanted to remove only my email address, but the extension applies "display:none" to the table that contains both elements rather than only to the data in the second cell (which is actually enclosed in a `<b>` element).

**_My settings:_**

> ![image](https://user-images.githubusercontent.com/59314/36415626-6c126550-15db-11e8-8c3c-b8a8b7f3ce8f.png)
-----
**_My results:_**

>  ![image](https://user-images.githubusercontent.com/59314/36415868-3e1bb1dc-15dc-11e8-842b-6c41710fb0fa.png)

**Comment by fcherman** [comment]
Okay, I fixed it by changing the first two items to reference the correct html elements (I also made the first item more specific for efficiency):

```
      if(hideGmailLogo) {
            $("div.bodycontainer table:first-child tbody td:first-child img[alt='Gmail']").parent().hide();          
        }
```

```
        if(hideEmail) {

            $("div.bodycontainer table:first-child tbody td:nth-child(2) b").hide();

     //       $("body > div > table").siblings("hr").hide();
    //        $("body > div > table").hide();
}
```

**Comment by Fogest** [comment]
Awesome! I am on the go right now and can apply the changes tomorrow to fix
it that you provided. Alternatively feel free to submit a pull request and
I'd be able to take a look at it and approve in case you want your work
attributed on Github.

Justin V

**Comment by fcherman** [comment]
I don't know how to do a pull request, but thanks anyway.

**Comment by ravenaus** [comment]
hi mate it stopped supporting the block on the mail.com logo again

any chance you can look at it please

**Comment by Fogest** [comment]
Oh my mistake I think I know what caused that. An update I made today may
have broken that. Will fix that in a few hours. The change may take longer
till it appears on your side :)

**Comment by Fogest** [comment]
Updated version pushed out, hopefully it starts working again for you in the next 3-12 hours.

**Comment by ravenaus** [comment]
hi

thank you its working again
